In [27]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [28]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head(5)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

In [30]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [31]:
df.head(5)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [32]:
X = df.iloc[:, 1:]
y = df.iloc[:, 0]

# Train test splite

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

##Scaling

In [34]:
scaler = StandardScaler()
X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)

In [35]:
type(X_test_scale)

numpy.ndarray

## Encode Target

In [36]:
encoder = LabelEncoder()
y_train_encode = encoder.fit_transform(y_train)
y_test_encode = encoder.transform(y_test)

## Numpy arrays to PyTorch tensors

In [37]:
X_train_tensor = torch.from_numpy(X_train_scale)
X_test_tensor = torch.from_numpy(X_test_scale)
y_train_tensor = torch.from_numpy(y_train_encode)
y_test_tensor = torch.from_numpy(y_test_encode)

In [51]:
class MyNN():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    return torch.sigmoid(z)

  # loss
  def loss(self, y, y_pred):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    loss = - (y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
    return loss

In [67]:
model = MyNN(X_train_tensor)

learning_rate = 0.1
epochs = 50

In [78]:
for epoch in range(epochs):
  y_pred = model.forward(X_train_tensor)

  loss = model.loss(y_train_tensor, y_pred)

  loss.backward()
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7031321335890648
Epoch: 2, Loss: 0.7016950210554898
Epoch: 3, Loss: 0.7003291689053925
Epoch: 4, Loss: 0.6990306306517677
Epoch: 5, Loss: 0.6977956804850856
Epoch: 6, Loss: 0.6966208003661071
Epoch: 7, Loss: 0.6955026681956739
Epoch: 8, Loss: 0.6944381468956927
Epoch: 9, Loss: 0.6934242742690314
Epoch: 10, Loss: 0.6924582535323126
Epoch: 11, Loss: 0.6915374444364312
Epoch: 12, Loss: 0.6906593549062273
Epoch: 13, Loss: 0.6898216331440117
Epoch: 14, Loss: 0.6890220601522339
Epoch: 15, Loss: 0.688258542639026
Epoch: 16, Loss: 0.687529106277048
Epoch: 17, Loss: 0.6868318892913674
Epoch: 18, Loss: 0.6861651363562552
Epoch: 19, Loss: 0.6855271927840264
Epoch: 20, Loss: 0.6849164989915593
Epoch: 21, Loss: 0.6843315852320343
Epoch: 22, Loss: 0.6837710665808802
Epoch: 23, Loss: 0.683233638165981
Epoch: 24, Loss: 0.6827180706329753
Epoch: 25, Loss: 0.6822232058370333
Epoch: 26, Loss: 0.6817479527528812
Epoch: 27, Loss: 0.6812912835951045
Epoch: 28, Loss: 0.6808522301409311
Epoch: 29, Loss: 0.6804298802478129
Epoch: 30, Loss: 0.6800233745582004
Epoch: 31, Loss: 0.67963190338397
Epoch: 32, Loss: 0.6792547037630179
Epoch: 33, Loss: 0.678891056680606
Epoch: 34, Loss: 0.6785402844481098
Epoch: 35, Loss: 0.6782017482319332
Epoch: 36, Loss: 0.6778748457254511
Epoch: 37, Loss: 0.6775590089569891
Epoch: 38, Loss: 0.6772537022270012
Epoch: 39, Loss: 0.6769584201677831
Epoch: 40, Loss: 0.6766726859192498
Epoch: 41, Loss: 0.6763960494145123
Epoch: 42, Loss: 0.6761280857692104
Epoch: 43, Loss: 0.6758683937687832
Epoch: 44, Loss: 0.6756165944480944
Epoch: 45, Loss: 0.6753723297580735
Epoch: 46, Loss: 0.6751352613142669
Epoch: 47, Loss: 0.6749050692224444
Epoch: 48, Loss: 0.6746814509766361
Epoch: 49, Loss: 0.6744641204252225
Epoch: 50, Loss: 0.6742528068009179

## Accuracy

In [79]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6228070259094238